name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 2.1.0
  Size: 5 Orgs with 1 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.hiam.hal:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.hiam.hal/users/User1@org1.hiam.hal/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.hiam.hal/users/User1@org1.hiam.hal/msp/signcerts/cert.pem

  client0.org2.hiam.hal:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.hiam.hal/users/User1@org2.hiam.hal/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.hiam.hal/users/User1@org2.hiam.hal/msp/signcerts/cert.pem

  client0.org3.hiam.hal:
    client:
      organization: Org3
      credentialStore:
        path: /tmp/hfc-kvs/org3
        cryptoStore:
          path: /tmp/hfc-cvs/org3
      clientPrivateKey:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.hiam.hal/users/User1@org3.hiam.hal/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.hiam.hal/users/User1@org3.hiam.hal/msp/signcerts/cert.pem

  client0.org4.hiam.hal:
    client:
      organization: Org4
      credentialStore:
        path: /tmp/hfc-kvs/org4
        cryptoStore:
          path: /tmp/hfc-cvs/org4
      clientPrivateKey:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.hiam.hal/users/User1@org4.hiam.hal/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.hiam.hal/users/User1@org4.hiam.hal/msp/signcerts/cert.pem

  client0.org5.hiam.hal:
    client:
      organization: Org5
      credentialStore:
        path: /tmp/hfc-kvs/org5
        cryptoStore:
          path: /tmp/hfc-cvs/org5
      clientPrivateKey:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.hiam.hal/users/User1@org5.hiam.hal/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.hiam.hal/users/User1@org5.hiam.hal/msp/signcerts/cert.pem

channels:
  mychannel:
    # configBinary: networks/fabric/pavan-v2.1/mychannel.tx
    created: true
    contracts: [{ "id": "fabcar", "version": "1" }]
    definition:
      capabilities: []
      consortium: "SampleConsortium"
      msps: ["Org1MSP", "Org2MSP", "Org3MSP"]
      version: 0
    orderers:
      - orderer.hiam.hal
      - orderer2.hiam.hal
      - orderer3.hiam.hal
    peers:
      peer0.org1.hiam.hal:
        eventSource: true
      peer0.org2.hiam.hal:
        eventSource: true
      peer0.org3.hiam.hal:
        eventSource: true
      # peer0.org4.hiam.hal:
      #   eventSource: true
      # peer0.org5.hiam.hal:
      #   eventSource: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.hiam.hal
    certificateAuthorities:
      - ca.org1.hiam.hal
    adminPrivateKey:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.hiam.hal/users/Admin@org1.hiam.hal/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.hiam.hal/users/Admin@org1.hiam.hal/msp/signcerts/cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.hiam.hal
    certificateAuthorities:
      - ca.org2.hiam.hal
    adminPrivateKey:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.hiam.hal/users/Admin@org2.hiam.hal/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.hiam.hal/users/Admin@org2.hiam.hal/msp/signcerts/cert.pem

  Org3:
    mspid: Org3MSP
    peers:
      - peer0.org3.hiam.hal
    certificateAuthorities:
      - ca.org3.hiam.hal
    adminPrivateKey:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.hiam.hal/users/Admin@org3.hiam.hal/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.hiam.hal/users/Admin@org3.hiam.hal/msp/signcerts/cert.pem

  Org4:
    mspid: Org4MSP
    peers:
      - peer0.org4.hiam.hal
    certificateAuthorities:
      - ca.org4.hiam.hal
    adminPrivateKey:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.hiam.hal/users/Admin@org4.hiam.hal/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.hiam.hal/users/Admin@org4.hiam.hal/msp/signcerts/cert.pem

  Org5:
    mspid: Org5MSP
    peers:
      - peer0.org5.hiam.hal
    certificateAuthorities:
      - ca.org5.hiam.hal
    adminPrivateKey:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.hiam.hal/users/Admin@org5.hiam.hal/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.hiam.hal/users/Admin@org5.hiam.hal/msp/signcerts/cert.pem

orderers:
  orderer.hiam.hal:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.hiam.hal
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/ordererOrganizations/hiam.hal/orderers/orderer.hiam.hal/msp/tlscacerts/tlsca.hiam.hal-cert.pem
  orderer2.hiam.hal:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer2.hiam.hal
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/ordererOrganizations/hiam.hal/orderers/orderer2.hiam.hal/msp/tlscacerts/tlsca.hiam.hal-cert.pem
  orderer3.hiam.hal:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer3.hiam.hal
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/ordererOrganizations/hiam.hal/orderers/orderer3.hiam.hal/msp/tlscacerts/tlsca.hiam.hal-cert.pem

peers:
  peer0.org1.hiam.hal:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.hiam.hal
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.hiam.hal/peers/peer0.org1.hiam.hal/tls/tlscacerts/tls-localhost-7054-ca-org1-example-com.pem

  peer0.org2.hiam.hal:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.hiam.hal
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.hiam.hal/peers/peer0.org2.hiam.hal/tls/tlscacerts/tls-localhost-8054-ca-org2-example-com.pem

  peer0.org3.hiam.hal:
    url: grpcs://localhost:11051
    grpcOptions:
      ssl-target-name-override: peer0.org3.hiam.hal
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.hiam.hal/peers/peer0.org3.hiam.hal/tls/tlscacerts/tls-localhost-10054-ca-org3-example-com.pem

  peer0.org4.hiam.hal:
    url: grpcs://localhost:12051
    grpcOptions:
      ssl-target-name-override: peer0.org4.hiam.hal
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.hiam.hal/peers/peer0.org4.hiam.hal/tls/tlscacerts/tls-localhost-11054-ca-org4-example-com.pem

  peer0.org5.hiam.hal:
    url: grpcs://localhost:13051
    grpcOptions:
      ssl-target-name-override: peer0.org5.hiam.hal
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.hiam.hal/peers/peer0.org5.hiam.hal/tls/tlscacerts/tls-localhost-12054-ca-org5-example-com.pem

certificateAuthorities:
  ca.org1.hiam.hal:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.hiam.hal/tlsca/tlsca.org1.hiam.hal-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org2.hiam.hal:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.hiam.hal/tlsca/tlsca.org2.hiam.hal-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org3.hiam.hal:
    url: https://localhost:10054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.hiam.hal/tlsca/tlsca.org3.hiam.hal-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org4.hiam.hal:
    url: https://localhost:11054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.hiam.hal/tlsca/tlsca.org4.hiam.hal-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org5.hiam.hal:
    url: https://localhost:12054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.hiam.hal/tlsca/tlsca.org5.hiam.hal-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
